name: flutter_insider
description: Flutter plugin wrapping the Insider mobile SDK for user tracking, custom events, push notifications, smart recommendations, and App Cards.
version: 5.0.3+nh
homepage: https://useinsider.com
repository: https://github.com/useinsider/flutter-insider
issue_tracker: https://github.com/useinsider/flutter-insider/issues
documentation: https://pub.dev/documentation/flutter_insider/latest/

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.useinsider.insider.flutter_insider
        pluginClass: FlutterInsiderPlugin
      ios:
        pluginClass: FlutterInsiderPlugin
